# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://szymanskilukasz.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: szymanskilukasz
  avatar:
  gravatar: 33d8f6c5f5c8b940ff4d6422a5f32b02
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "szymanskilukasz"
  google_plus:
  instagram:
  linkedin: "http://pl.linkedin.com/in/szymanskilukasz"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "szymanskilukasz"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: szymanskilukasz
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
